server:
  port: 8081

spring:
  application:
    name: fs2604-raja-rainfall-trigger

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

integration:
  ganesh:
    base-url: "http://localhost:8080"
  anosh:
    base-url: "http://localhost:8082"
